---
hostname: RT1-Pl

l3_interfaces:
  - name: "{{ rInt['Gig0/2'] }}"
    description: "Connection to Wan"
    ipv4:
      dhcp: True

  - name: Loopback0
    description: "Engineering Network"
    ipv4:
      address: 172.20.11.1
      prefix: 24
    ipv6:
      address: "2001:B::1/64"
  
  - name: Loopback2
    description: "Communication Network"
    ipv4:
      address: 172.20.9.129
      prefix: 25
    ipv6:
      address: "2001:B:0:2::1/64"

subinterfaces:
  - parent: "{{ rInt['Gig0/1'] }}"
    vlan: 5
    description: "Trunk for Vlan 5 APs"
    ipv4:
      address: 172.20.8.153
      prefix: 29
    ipv6:
      address: "2001:B:0:6::1/64"
  
  - parent: "{{ rInt['Gig0/1'] }}"
    vlan: 6
    description: "Trunk for Vlan 6 Management"
    ipv4:
      address: 172.20.8.145
      prefix: 29
    ipv6:
      address: "2001:B:0:7::1/64"
  
  - parent: "{{ rInt['Gig0/1'] }}"
    vlan: 30
    description: "Trunk for Vlan 30 Staff"
    ipv4:
      address: 172.20.9.1
      prefix: 25
    ipv6:
      address: "2001:B:0:3::1/64"
      dhcpv6_pool: "Staff-v6"
  
  - parent: "{{ rInt['Gig0/1'] }}"
    vlan: 40
    description: "Trunk for Vlan 40 VoIP"
    ipv4:
      address: 172.20.8.161
      prefix: 27
    ipv6:
      address: "2001:B:0:1::1/64"
  
  - parent: "{{ rInt['Gig0/1'] }}"
    vlan: 50
    description: "Trunk for Vlan 50 Wireless"
    ipv4:
      address: 172.20.10.1
      prefix: 24
    ipv6:
      address: "2001:B:0:4::1/64"
      dhcpv6_pool: "Wireless-Pl-v6"
  
  - parent: "{{ rInt['Gig0/1'] }}"
    vlan: 60
    description: "Trunk for Vlan 60 Guests"
    ipv4:
      address: 172.20.8.193
      prefix: 26
    ipv6:
      address: "2001:B:0:5::1/64"
      dhcpv6_pool: "Guests-Pl-v6"

dhcp_pools:
  - name: Staff
    network:
      address: 172.20.9.0
      netmask: 255.255.255.128
    gateway:
      default_router: 172.20.9.1
    excluded:
      start: 172.20.9.0
      end: 172.20.9.5

  - name: VoIP
    network:
      address: 172.20.8.160
      netmask: 255.255.255.224
    gateway:
      default_router: 172.20.8.161
    excluded:
      start: 172.20.8.160
      end: 172.20.8.165
  
  - name: Wireless-Pl
    network:
      address: 172.20.10.0
      netmask: 255.255.255.0
    gateway:  
      default_router: 172.20.10.1
    excluded:
      start: 172.20.10.0
      end: 172.20.10.5
  
  - name: Guests-Pl
    network:
      address: 172.20.8.192
      netmask: 255.255.255.192
    gateway:
      default_router: 172.20.8.193
    excluded:
      start: 172.20.8.192
      end: 172.20.8.197

dhcpv6_pools:
  - name: Staff-v6
    prefix: "2001:B:0:3::/64"

  - name: VoIP-v6
    prefix: "2001:B:0:1::/64"
  
  - name: Wireless-Pl-v6
    prefix: "2001:B:0:4::/64"
  
  - name: Guests-Pl-v6
    prefix: "2001:B:0:5::/64"

gre_tunnels:
  - name: Tunnel0
    description: Pula to Zagreb
    ip: 10.0.0.2
    mask: 255.255.255.252
    source: 172.16.201.194
    destination: 172.16.201.193

  - name: Tunnel2
    description: Pula to Split
    ip: 10.0.0.9
    mask: 255.255.255.252
    source: 172.16.201.194
    destination: 172.16.201.195
    
ipsec_peers:
  - address: 172.16.201.193
    key: z4gr3bPvl4
    acl_name: ZAGREB-ACL-PULA
    src_ip: 172.16.201.194
    dst_ip: 172.16.201.193
    seq: 10

  - address: 172.16.201.195
    key: Pvl4$pl1t
    acl_name: PULA-ACL-SPLIT
    src_ip: 172.16.201.194
    dst_ip: 172.16.201.195
    seq: 30

ospf_processes:
  - process_id: 100
    router_id: 2.2.2.2
    passive_interfaces:
      - Loopback0
      - Loopback2
    active_interfaces:
      - "{{ rInt['Gig0/1'] }}.5"
      - "{{ rInt['Gig0/1'] }}.6"
      - "{{ rInt['Gig0/1'] }}.30"
      - "{{ rInt['Gig0/1'] }}.40"
      - "{{ rInt['Gig0/1'] }}.50"
      - "{{ rInt['Gig0/1'] }}.60"
      - "{{ rInt['Gig0/2'] }}"
      - Tunnel0
      - Tunnel2
      - Loopback0
      - Loopback2

static_routes:
  # Default route
  - dest: "0.0.0.0"
    prefix: 0
    next_hop: "172.16.201.254"

nat:
  inside_interfaces:
    - "{{ rInt['Gig0/1'] }}.5"
    - "{{ rInt['Gig0/1'] }}.6"
    - "{{ rInt['Gig0/1'] }}.30"
    - "{{ rInt['Gig0/1'] }}.40"
    - "{{ rInt['Gig0/1'] }}.50"
    - "{{ rInt['Gig0/1'] }}.60"
  outside_interface: "{{ rInt['Gig0/2'] }}"

nat_acl:
  name: NAT_ACL
  entries:
    - ace:
        sequence: 10
        grant: deny
        source:
          address: 172.20.8.160
          wildcard_bits: 0.0.0.31
    - ace:
        sequence: 20
        grant: permit
        source:
          address: 172.20.8.0
          wildcard_bits: 0.0.3.255

static_nat:
  - inside_ip: 172.20.8.146
    outside_interface: "{{ rInt['Gig0/2'] }}"
    port_local: 22
    port_global: 2225

guest_acl:
  name: GUEST_ACL
  entries:
    - ace: # Deny access to internal networks
        sequence: 10
        grant: deny
        protocol: ip
        source: 
          address: 172.20.8.192
          wildcard_bits: 0.0.0.63
        destination:
          address: 172.20.0.0
          wildcard_bits: 0.0.255.255
    - ace: # Deny access to VPN networks
        sequence: 20
        grant: deny
        protocol: ip
        source:
          address: 172.20.8.192
          wildcard_bits: 0.0.0.63
        destination:
          address: 10.0.0.0
          wildcard_bits: 0.0.0.15
    - ace: # Allow access to the Internet
        sequence: 30
        grant: permit
        protocol: ip
        source:
          address: 172.20.8.192
          wildcard_bits: 0.0.0.63
        destination:
          any: true