---
hostname: RT1-Zg

l3_interfaces:
  - name: "{{ rInt['Gig0/0'] }}"
    description: "Connection to MLS1-Zg"
    ipv4:
      address: 172.20.0.157
      prefix: 30
    ipv6:
      address: "2001:A:0:8::1/64"
  
  - name: "{{ rInt['Gig0/1'] }}"
    description: "Connection to MLS2-Zg"
    ipv4:
      address: 172.20.0.153
      prefix: 30
    ipv6:
      address: "2001:A:0:9::1/64"

  - name: "{{ rInt['Gig0/2'] }}"
    description: "Connection to Wan"
    ipv4:
      # dhcp: True
      address: 172.16.201.201
      prefix: 24

  - name: Loopback0
    description: "NTP Server"
    ipv4:
      address: 203.0.113.1
      prefix: 32
    ipv6:
      address: "2001:D::1/64"

gre_tunnels:
  - name: Tunnel0
    description: Zagreb to Pula
    ip: 10.0.0.1
    mask: 255.255.255.252
    source: 172.16.201.201
    destination: 172.16.201.202

  - name: Tunnel1
    description: Zagreb to Split
    ip: 10.0.0.5
    mask: 255.255.255.252
    source: 172.16.201.201
    destination: 172.16.201.202
    
ipsec_peers:
  - address: 172.16.201.202
    key: z4gr3bPvl4
    acl_name: ZAGREB-ACL-PULA
    src_ip: 172.16.201.201
    dst_ip: 172.16.201.202

  - address: 172.16.201.200
    key: z4gr3b$pl1t
    acl_name: ZAGREB-ACL-SPLIT
    src_ip: 172.16.201.201
    dst_ip: 172.16.201.200

ospf_processes:
  - process_id: 100
    router_id: 1.1.1.1
    passive_interfaces:
      - Loopback0
    active_interfaces:
      - "{{ rInt['Gig0/0'] }}"
      - "{{ rInt['Gig0/1'] }}"
      - "{{ rInt['Gig0/2'] }}"
      - Tunnel0
      - Tunnel1
      - Loopback0

static_routes:
  # Default route
  - dest: "0.0.0.0"
    prefix: 0
    next_hop: "172.16.201.254"

nat:
  inside_interfaces:
    - "{{ rInt['Gig0/0'] }}"
    - "{{ rInt['Gig0/1'] }}"
  outside_interface: "{{ rInt['Gig0/2'] }}"

nat_acl:
  name: NAT_ACL
  entries:
    - ace:
        sequence: 10
        grant: deny
        source:
          address: 172.20.6.0
          wildcard_bits: 0.0.1.255
    - ace:
        sequence: 20
        grant: permit
        source:
          address: 172.20.0.0
          wildcard_bits: 0.0.7.255

static_nat:
  - inside_ip: 172.20.0.196
    outside_interface: "{{ rInt['Gig0/2'] }}"
    port_local: 80
    port_global: 80

  - inside_ip: 172.20.0.196
    outside_interface: "{{ rInt['Gig0/2'] }}"
    port_local: 443
    port_global: 443

  # - proto: tcp
  #   inside_ip: 172.20.0.196
  #   outside_interface: "{{ rInt['Gig0/2'] }}"
  #   port_local: 22
  #   port_global: 22

  - inside_ip: 172.20.0.196
    outside_interface: "{{ rInt['Gig0/2'] }}"
    port_local: 22
    port_global: 2222

  - inside_ip: 172.20.0.158
    outside_interface: "{{ rInt['Gig0/2'] }}"
    port_local: 22
    port_global: 2223
    
  - inside_ip: 172.20.0.154
    outside_interface: "{{ rInt['Gig0/2'] }}"
    port_local: 22
    port_global: 2224

  - inside_ip: 172.20.0.228
    outside_interface: "{{ rInt['Gig0/2'] }}"
    port_local: 22
    port_global: 2225
    
  - inside_ip: 172.20.0.229
    outside_interface: "{{ rInt['Gig0/2'] }}"
    port_local: 22
    port_global: 2226
ntp:
  servers:
    - 216.239.35.12
    - 216.239.35.8
    - 216.239.35.0
    - 216.239.35.4
  master:
    enabled: true
    stratum: 2
    source: Loopback0
