# =============================================
# FILE: inventory.yml
# =============================================
---
all:
  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: cisco.ios.ios
    ansible_user: cisco
    ansible_password: "classclass"
    ansible_become: yes
    ansible_become_method: enable
    ansible_become_password: "classclass"
  children:
    layer3:
      children:
        routers:
          hosts:
            RT1-Zg:
              ansible_host: 172.16.201.193
            RT1-Pl:
              ansible_host: 172.16.201.194
            RT1-St:
              ansible_host: 172.16.201.195
        servers:
          hosts:
            DHCP-SRV:
              # ansible_host: 172.20.0.196
              ansible_host: 172.16.201.193
              ansible_port: 2222
    layer23:
      children:
        mls:
          hosts:
            MLS1-Zg:
              # ansible_host: 172.20.0.158
              ansible_host: 172.16.201.193
              ansible_port: 2223
            MLS2-Zg:
              # ansible_host: 172.20.0.154
              ansible_host: 172.16.201.193
              ansible_port: 2224
    layer2:
      children:
        access_switches:
          hosts:
            SW1-Zg:
              # ansible_host: 172.20.0.228
              ansible_host: 172.16.201.193
              ansible_port: 2225
            SW2-Zg:
              # ansible_host: 172.20.0.229
              ansible_host: 172.16.201.193
              ansible_port: 2226
            SW1-Pl:
              # ansible_host: 172.20.8.146
              ansible_host: 172.16.201.194
              ansible_port: 2225
            SW1-St:
              # ansible_host: 172.20.12.18
              ansible_host: 172.16.201.195
              ansible_port: 2225