---
- name: CCNA3 Project - Tasks Playbook
  hosts: all
  gather_facts: no

  tasks:
    # Part 4: IPSEC VPN Tunnels -----------------------------------
    - name: Configure ISAKMP Policy 100
      cisco.ios.ios_config:
        lines:
          - encr aes 128
          - hash sha
          - authentication pre-share
          - group 5
        parents: crypto isakmp policy 100
      when: ipsec_peers is defined
      tags: ipsec

    - name: Configure ISAKMP Pre-shared Keys
      cisco.ios.ios_config:
        lines:
          - crypto isakmp key {{ item.key }} address {{ item.address }}
      loop: "{{ ipsec_peers }}"
      when: ipsec_peers is defined
      tags: ipsec

    - name: Configure IPsec Transform Set
      cisco.ios.ios_config:
        lines:
          - crypto ipsec transform-set TSET esp-aes esp-sha-hmac
      when: ipsec_peers is defined
      tags: ipsec

    - name: Configure Crypto Map
      cisco.ios.ios_config:
        lines:
          - set peer {{ item.address }}
          - set transform-set TSET
          - match address {{ item.acl_name }}
        parents: crypto map CROATIA {{ item.seq }} ipsec-isakmp
      loop: "{{ ipsec_peers }}"
      when: ipsec_peers is defined
      tags: ipsec

    - name: Configure Tunnels
      cisco.ios.ios_interfaces:
        config:
          - name: "{{ item.name }}"
            description: "{{ item.description }}"
        state: merged
      loop: "{{ tunnels }}"
      when: tunnels is defined
      tags: tunnels

    - name: Configure Tunnel IP addresses
      cisco.ios.ios_l3_interfaces:
        config:
          - name: "{{ item.name }}"
            ipv4:
              - address: "{{ item.ipv4.address }}/{{ item.ipv4.prefix }}"
        state: merged
      loop: "{{ tunnels }}"
      when: tunnels is defined
      tags: tunnels

    - name: Configure Tunnel source and destination
      cisco.ios.ios_config:
        lines:
          - "tunnel source {{ item.tunnel.source }}"
          - "tunnel destination {{ item.tunnel.destination }}"
        parents: "interface {{ item.name }}"
      loop: "{{ tunnels }}"
      when: tunnels is defined
      tags: tunnels

    - name: Apply Crypto Map to WAN interfaces
      cisco.ios.ios_config:
        lines:
          - crypto map CROATIA
        parents: interface {{ rInt['Gig0/2'] }}
      when: 
        - ipsec_peers is defined
      tags: ipsec

    - name: Configure ACLs for IPsec
      cisco.ios.ios_acls:
        config:
          - afi: ipv4
            acls:
            - name: "{{ item.acl_name }}"
              acl_type: extended
              aces: "{{ item.entries | map(attribute='ace') | list }}"
        state: replaced
      loop: "{{ ipsec_acls }}"
      when: ipsec_acls is defined
      tags: ipsec_acl

    # Part 5: Routing -------------------------------------
    - name: Delete provided OSPF outside interface
      cisco.ios.ios_ospf_interfaces:
        config:
          - name: "{{ rInt['Gig0/2'] }}"
        state: deleted
      when: 
        - ospf is defined
        - "'routers' in group_names"
      tags: ospf

    - name: Configure OSPF process
      cisco.ios.ios_ospfv2:
        config:
          processes:
            - process_id: 100
              router_id: "{{ ospf.router_id }}"
              default_information:
                originate: "{{ 'routers' in group_names }}"
        state: replaced
      when: ospf is defined
      tags: ospf

    - name: Configure OSPF on interfaces
      cisco.ios.ios_ospf_interfaces:
        config:
          - name: "{{ item }}"
            address_family:
              - afi: ipv4
                process:
                  id: 100
                  area_id: 0
        state: merged
      loop: "{{ ospf.interfaces }}"
      when: ospf is defined
      tags: ospf

    - name: Configure OSPF passive interfaces
      cisco.ios.ios_ospfv2:
        config:
          processes:
            - process_id: 100
              passive_interfaces:
                interface:
                  set_interface: true
                  name: "{{ item }}"
        state: merged
      loop: "{{ ospf.passive_interfaces }}"
      when: ospf is defined
      tags: ospf

    # Part 6 Static and Dynamic NAT ---------------------------------
    - name: Configure NAT ACL
      cisco.ios.ios_acls:
        config:
          - afi: ipv4
            acls:
              - name: "{{ nat_acl.name }}"
                acl_type: standard
                aces: "{{ nat_acl.entries | map(attribute='ace') | list }}"
        state: replaced
      when: nat_acl is defined
      tags: nat_acl

    - name: Configure NAT inside interfaces
      cisco.ios.ios_config:
        lines:
          - ip nat inside
        parents: "interface {{ item }}"
      loop: "{{ nat.inside_interfaces }}"
      when: nat is defined
      tags: nat

    - name: Configure NAT outside interface
      cisco.ios.ios_config:
        lines:
          - ip nat outside
        parents: "interface {{ nat.outside_interface }}"
      when: nat is defined
      tags: nat

    - name: Configure PAT
      cisco.ios.ios_config:
        lines:
          - "ip nat inside source list {{ nat_acl.name }} interface {{ nat.outside_interface }} overload"
      when: nat is defined and nat_acl is defined
      tags: nat

    - name: Bind NAT ACL to outside interface
      cisco.ios.ios_config:
        lines:
          - "ip nat inside source static tcp {{ item.inside_ip }} {{ item.port_local }} interface {{ item.outside_interface }} {{ item.port_global }}"
      loop: "{{ static_nat }}"
      when: static_nat is defined
      tags: static_nat

    - name: Configure HTTP server on DHCP-SRV
      cisco.ios.ios_config:
        lines:
          - ip http server
          - ip http secure-server
          - ip http authentication local
      when: "'servers' in group_names"
      tags: http

    # Part 7: Telephony Services
    - name: Configure VoIP option
      cisco.ios.ios_config:
        lines:
          - "option 150 ip {{ voip_phones.gtw }}"
        parents: "ip dhcp pool VoIP"
      when: voip_phones is defined
      tags: voip

    - name: Configure telephony service
      cisco.ios.ios_config:
        lines:
          - "max-ephones 58"
          - "max-dn 128"
          - "ip source-address {{ voip_phones.gtw }} port 2000"
          - "system message {{ voip_phones.msg }}"
          - "cnf-file location flash:"
          - "load 7912 CP7912080004SCCP080108A.sbin"
          - "create cnf-files"
        parents: "telephony-service"
      when: voip_phones is defined
      tags: voip

    - name: Configure extensions-dn for VoIP phones
      cisco.ios.ios_config:
        lines:
          - "number {{ item.ext }}"
        parents: "ephone-dn {{ item.name }}"
      loop: "{{ voip_phones.lines }}"
      when: voip_phones is defined
      tags: voip

    - name: Configure extensions for VoIP phones
      cisco.ios.ios_config:
        lines:
          - "mac-address {{ item.mac }}"
          - "type 7912"
          - "button 1:{{ item.name }}"
        parents: "ephone {{ item.name }}"
      loop: "{{ voip_phones.lines }}"
      when: voip_phones is defined
      tags: voip

    - name: Configure dial-peer for VoIP phones
      cisco.ios.ios_config:
        lines:
          - "description OUTGOING CALLS"
          - "destination-pattern {{ item.pattern }}"
          - "session target ipv4:{{ item.ip }}"
        parents: "dial-peer voice {{ item.name }} voip"
      loop: "{{ voip_phones.dial_peers }}"
      when: voip_phones is defined
      tags: voip

    # Part 8: NTP ------------------------------------
    - name: Configure NTP upstream servers
      cisco.ios.ios_ntp_global:
        config:
          servers:
            - server: "{{ item }}"
          master:
            stratum: "{{ ntp.master.stratum }}"
          source: "{{ ntp.master.source }}"
        state: merged
      loop: "{{ ntp.servers }}"
      when: ntp.master.enabled
      tags: ntp

    - name: Configure NTP client
      cisco.ios.ios_ntp_global:
        config:
          servers:
            - server: "{{ ntp.client.server }}"
        state: replaced
      when: not ntp.master.enabled
      tags: ntp

      # Part 9: Syslog and SNMP ---------------------------------
    - name: Configure SNMPv2c
      cisco.ios.ios_snmp_server:
        config:
          communities:
            - name: "{{ snmp.community }}"
              ro: "{{ snmp.access == 'ro' }}"
              # acl_v4: "{{ snmp_acl.name if snmp_acl is defined else omit }}"
        state: replaced
      when: snmp is defined
      tags: snmp

    - name: Configure Syslog server
      cisco.ios.ios_config:
        lines:
          - "logging host {{ syslog.server }}"
          - "logging trap {{ syslog.trap }}"
          - "logging on"
      when: syslog is defined
      tags: syslog

    - name: Save Configuration
      cisco.ios.ios_config:
        save_when: always
      tags: save