---
# - name: Configure SNMP ACL
#   cisco.ios.ios_acls:
#     config:
#       - afi: ipv4
#         acls:
#           - name: "{{ snmp_acl.name }}"
#             acl_type: standard
#             aces: "{{ snmp_acl.entries | map(attribute='ace') | list }}"
#     state: deleted
#   when: snmp_acl is defined
#   tags: snmp

# - name: Configure SNMPv2c
#   cisco.ios.ios_snmp_server:
#     config:
#       communities:
#         - name: "{{ snmp.community }}"
#           ro: "{{ snmp.access == 'ro' }}"
#           acl_v4: "{{ snmp_acl.name if snmp_acl is defined else omit }}"
#     state: deleted
#   when: snmp is defined
#   tags: snmp

# - name: Configure Syslog server
#   cisco.ios.ios_config:
#     lines:
#       - "no logging host {{ syslog.server }}"
#       - "no logging trap {{ syslog.trap }}"
#       # - "no logging on"
#   when: syslog is defined
#   tags: syslog

# - name: Configure SSH ACL
#   cisco.ios.ios_acls:
#     config:
#       - afi: ipv4
#         acls:
#           - name: "{{ ssh_acl.name }}"
#             acl_type: standard
#             aces: "{{ ssh_acl.entries | map(attribute='ace') | list }}"
#     state: deleted
#   when: ssh_acl is defined
#   tags: ssh

- name: Configure IP Host Entries
  cisco.ios.ios_config:
    lines:
      - "ip host {{ item.name }} {{ item.ip }}"
  loop: "{{ ip_hosts | default([]) }}"
  when: ip_hosts is defined
  diff: yes
  tags: hosts

# - name: Configure VTY ACL
#   cisco.ios.ios_config:
#     lines:
#       - "access-class {{ ssh_acl.name }} in"
#     parents: "line vty 0 4"
#   when: ssh_acl is defined
#   tags: vty_acl

- name: Save Configuration
  cisco.ios.ios_config:
    save_when: always
  tags: save


